CREATE TABLE IF NOT EXISTS Messages (
    sessionId TEXT PRIMARY KEY, 
    messages TEXT
);
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('868ab24a-d0e0-11ee-bad7-666fa1bdfbee', '[{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('b7133ad0-d0e0-11ee-9595-c66d174d70e4', '[{"content":"who is enrique ?","role":"user"},{"content":"Enrique Lores is the President and CEO of HP Inc., a global technology leader.","role":"assistant"},{"content":"Yes, Enrique Lores is a speaker at the HP Amplify Partner Conference 2024.","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('cbf228f9-d0f1-11ee-9595-c66d174d70e4', '[{"content":"o","role":"user"},{"content":"Hello! How can I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"},{"content":"Of course! I''m here to provide information about the HP Amplify Partner Conference 2024. What specific information are you looking for?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('f63c5aca-d0f2-11ee-9595-c66d174d70e4', '[{"content":"Tell me something interesting about the event.","role":"user"},{"content":"The HP Amplify Partner Conference 2024 is a premier event where HP partners gather to explore the latest innovations and strategies in the technology industry. It offers a unique opportunity for networking and collaboration among industry professionals.","role":"assistant"},{"content":"Who is? Enrique Lowers.","role":"user"},{"content":"Enrique Lores is the President and CEO of HP Inc. He leads the company in its mission to provide innovative products and services in the technology industry.","role":"assistant"},{"content":"What time does the event start?","role":"user"},{"content":"The event starts at 11:30 AM on Wednesday, March 6, 2024.","role":"assistant"},{"content":"The Expo at the HP Amplify Partner Conference showcases a wide range of products and solutions, including consumer PCs, gaming devices, printing technologies, workforce solutions, commercial products, and sustainability initiatives. It''s a hub of innovation and a great opportunity to explore the latest advancements in the industry.","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('53c9a377-d0f3-11ee-9595-c66d174d70e4', '[{"content":"Where''s the closest restroom?","role":"user"},{"content":"For the closest restrooms, please use the interactive map that is located on the home screen of the APC Mobile app for detailed locations.","role":"assistant"},{"content":"Tell me something interesting about the event.","role":"user"},{"content":"The HP Amplify Partner Conference 2024 offers an exciting opportunity for partners to explore the latest innovations and technologies in the HP ecosystem, fostering collaboration and growth.","role":"assistant"},{"content":"Where can I find products on print and printers?","role":"user"},{"content":"Print products and printers can be found in the Innovation Showcase, specifically in Hall B.","role":"assistant"},{"content":"Can you tell me?","role":"user"},{"content":"Hmm, I am not sure.","role":"assistant"},{"content":"Who is lost and found?","role":"user"},{"content":"Hmm, I am not sure.","role":"assistant"},{"content":"Where is lost and found?","role":"user"},{"content":"For lost and found inquiries, please visit the APC event registration check-in located outside of Expo Hall Foyer Outside of Hall C.","role":"assistant"},{"content":"Can you tell me what time the women''s lunch is?","role":"user"},{"content":"Certainly! The women''s lunch is scheduled for Wednesday, March 6, 2024, from 12:30 PM to 1:30 PM.","role":"assistant"},{"content":"Where is the casino located?","role":"user"},{"content":"For the casino location, please use the interactive map that is located on the home screen of the APC Mobile app for detailed locations.","role":"assistant"},{"content":"Only individuals that are registered for APC 2024 are allowed into the show. If there are any other questions or concerns, please contact an HP representative for additional information.","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('374a4fb3-d0f4-11ee-bad7-666fa1bdfbee', '[{"content":"Hello, tell me something interesting about the Expo.","role":"user"},{"content":"The Expo at the HP Amplify Partner Conference 2024 showcases the latest innovations and technologies from HP, providing an immersive experience for attendees to explore and engage with cutting-edge products and solutions.","role":"assistant"},{"content":"I am AI Concierge, here to assist you with any questions you have about the HP Amplify Partner Conference 2024. How may I assist you?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('05d8f313-d0f6-11ee-bad7-666fa1bdfbee', '[{"content":"My name is AI Concierge. How may I assist you?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('bdc5cb36-d0f6-11ee-9595-c66d174d70e4', '[{"content":"The Expo at the HP Amplify Partner Conference is a showcase of the latest HP technologies and innovations, providing attendees with a hands-on experience of the future of computing.","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('14a65d8a-d0f7-11ee-bad7-666fa1bdfbee', '[{"content":"What is your name?","role":"user"},{"content":"My name is AI Concierge. How may I assist you?","role":"assistant"},{"content":"hello","role":"user"},{"content":"Hello! How may I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"},{"content":"Hello! How may I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('52461899-d13e-11ee-bad7-666fa1bdfbee', '[{"content":"Hello! How can I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('d435a21b-d149-11ee-9595-c66d174d70e4', '[{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('8fbbb5c9-d14e-11ee-9595-c66d174d70e4', '[{"content":"Hello! How can I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('50a9a7d8-d14f-11ee-9595-c66d174d70e4', '[{"content":"Hello! How can I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('6a4ca600-d14f-11ee-bad7-666fa1bdfbee', '[{"content":"Hi","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hiii","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('7c690da9-d14f-11ee-bad7-666fa1bdfbee', '[{"content":"Hello! How can I assist you with the HP Amplify Partner Conference 2024?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('9a304373-d14f-11ee-9595-c66d174d70e4', '[{"content":"Hi","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hiiiiiiiii","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hiiiiiiiiii how are you ","role":"user"},{"content":"Hello! As an AI concierge, I don''t have feelings, but I''m here to assist you with any questions you may have about the HP Amplify Partner Conference 2024. How can I help you?","role":"assistant"},{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('c808df87-d14f-11ee-bad7-666fa1bdfbee', '[{"content":"Hi","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('967049de-d150-11ee-bad7-666fa1bdfbee', '[{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('8ff437db-d151-11ee-bad7-666fa1bdfbee', '[{"content":"Hi","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('acdccf81-d151-11ee-9595-c66d174d70e4', '[{"content":"Hi","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hello! How can I assist you today?","role":"assistant"}]');
INSERT INTO "Messages" ("sessionId", "messages") VALUES ('fb641f48-d151-11ee-bad7-666fa1bdfbee', '[{"content":"Hi","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hi.","role":"user"},{"content":"Hello! How can I assist you today?","role":"assistant"},{"content":"Hello! How can I assist you today?","role":"assistant"}]');